### ISSUE TITLE
Error with railsexpress ruby

### ISSUE THREAD

**Issue by acosonic** [Restream/redmine_reminder#5]
It sends email to some users, but not all...

```
redmine@rednune:~/redmine-3.3$ bundle exec rake redmine:send_reminders_all RAILS_ENV=production --trace
** Invoke redmine:send_reminders_all (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:send_reminders_all
rake aborted!
NoMethodError: undefined method `active?' for #<Group:0x000000092aac20>
Did you mean?  acts_like?
/home/redmine/.rvm/gems/ruby-2.3.3-railsexpress/gems/activemodel-4.2.7.1/lib/active_model/attribute_methods.rb:433:in `method_missing'
```

**Comment by acosonic** [comment]
I have resolved it by adding...

```
def active?
    self.status == STATUS_ACTIVE
  end

```
to group.rb model...

**Comment by acosonic** [comment]
Requested this, but... https://www.redmine.org/issues/27510

**Comment by pielat** [comment]
I have similiar problem. I've added your code into group.rb, but still I have error like this:

rake aborted!
NoMethodError: undefined method `active?' for #<Group:0x0000556f0add2a60>
Did you mean?  acts_like?
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_reminder/lib/tasks/reminder_all.rake:33:in `block (3 levels) in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_reminder/lib/tasks/reminder_all.rake:32:in `each'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_reminder/lib/tasks/reminder_all.rake:32:in `block (2 levels) in <top (required)>'
Tasks: TOP => redmine:send_reminders_all
(See full trace by running task with --trace)

Of course after adding the code I've migrated plugins end restarted apache.
